### ISSUE TITLE
[BUG] kms server died or never started, exit code: 1

### ISSUE THREAD

**Issue by anischenk0** [dec05eba/gpu-screen-recorder-issues#49] opened 2024-09-17 15:12 UTC
Hello.

Upon using the command

`$ flatpak run --command=gpu-screen-recorder com.dec05eba.gpu_screen_recorder -w screen -f 30 -o video.mp4`

The console returns:

`Warning: failed to connect to the X server. Assuming wayland is running without Xwayland
Info: using h264 encoder because a codec was not specified
gsr info: gsr_kms_client_init: waiting for server to connect
Can't find bus: Cannot autolaunch D-Bus without X11 $DISPLAY
gsr error: gsr_kms_client_init: kms server died or never started, exit code: 1
gsr error: gsr_capture_start failed`

Similarly, `$ flatpak run com.dec05eba.gpu_screen_recorder` returns

`Warning: failed to connect to the X server. Assuming wayland is running without Xwayland
gsr error: gsr_dbus_init: dbus_bus_get failed with error: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11`

`(gpu-screen-recorder-gtk:2): Gdk-WARNING **: 12:08:50.399: Settings portal not found: Cannot autolaunch D-Bus without X11 $DISPLAY`

The package for Xwayland on void linux, "xorg-server-xwayland" is installed. Attempted on Sway wm.
Have a nice day.

**Comment by anischenk0** [comment] 2024-09-18 00:04
Hello.
Yes, the program fails to record. I have posted the full contents of the
terminal. In the first case it exits, in the second it gets stuck at what
you see there.

**Comment by dec05eba** [comment] 2024-09-18 08:55
Did you try the steps described above? also something might be wrong with flatpak on your system, have you tried if other flatpak applications work? for example try this: https://flathub.org/apps/nl.hjdskes.gcolor3

**Comment by dec05eba** [comment] 2024-09-26 13:33
Is this still an issue?

**Comment by anischenk0** [comment] 2024-09-28 17:51
> Did you try the steps described above? also something might be wrong with flatpak on your system, have you tried if other flatpak applications work? for example try this: https://flathub.org/apps/nl.hjdskes.gcolor3

Hello! Sorry, I didn't see the steps you described because I replied directly to the email and the text was either missing from it or I screwed up. In any case, the steps led to the same error.

I tried the color picker flatpak you sent and it works no problem.

Yes, this is still an issue. Thank you for your time and patience.

**Comment by dec05eba** [comment] 2024-09-28 17:54
Did you also try the other steps I mentioned?

> can you run sudo rm -rf ~/.local/share/gpu-screen-recorder/ and try running that same flatpak run --command=gpu-screen-recorder com.dec05eba.gpu_screen_recorder -w screen -f 30 -o video.mp4 command again?

**Comment by anischenk0** [comment] 2024-09-28 17:56
> Did you also try the other steps I mentioned?
> 
> > can you run sudo rm -rf ~/.local/share/gpu-screen-recorder/ and try running that same flatpak run --command=gpu-screen-recorder com.dec05eba.gpu_screen_recorder -w screen -f 30 -o video.mp4 command again?

Yes, I did. They returned the same error as the first post:

`Warning: failed to connect to the X server. Assuming wayland is running without Xwayland`
`Info: using h264 encoder because a codec was not specified`
`gsr info: gsr_kms_client_init: waiting for server to connect`
`Can't find bus: Cannot autolaunch D-Bus without X11 $DISPLAY`
`gsr error: gsr_kms_client_init: kms server died or never started, exit code: 1`
`gsr error: gsr_capture_start failed`

**Comment by dec05eba** [comment] 2024-09-28 18:00
Try this, run `ls /dev/dri/card*` to see which files you have available and then use the first one and run:
```
flatpak run --command=bash com.dec05eba.gpu_screen_recorder
flatpak-spawn --host /var/lib/flatpak/app/com.dec05eba.gpu_screen_recorder/current/active/files/bin/kms-server-proxy blabla /dev/dri/card0 $HOME
```
replace /dev/dri/card0 there with the /dev/dri/cardN file that is available on your computer

**Comment by anischenk0** [comment] 2024-09-28 18:04
> flatpak-spawn --host /var/lib/flatpak/app/com.dec05eba.gpu_screen_recorder/current/active/files/bin/kms-server-proxy blabla /dev/dri/card0 $HOME

card0 was the one available to me. Upon entering the first command, the terminal just returned to prompt again, no message. Then:
`flatpak-spawn --host /var/lib/flatpak/app/com.dec05eba.gpu_screen_recorder/current/active/files/bin/kms-server-proxy blabla /dev/dri/card0 $HOME`
`Can't find bus: Cannot autolaunch D-Bus without X11 $DISPLAY`

**Comment by dec05eba** [comment] 2024-09-28 18:09
Can you run `echo $DBUS_SESSION_BUS_ADDRESS` in a new terminal and also
```
flatpak run --command=bash com.dec05eba.gpu_screen_recorder
echo $DBUS_SESSION_BUS_ADDRESS
```

**Comment by anischenk0** [comment] 2024-09-28 18:11
> echo $DBUS_SESSION_BUS_ADDRESS

Opened a new terminal, did the first echo, then the next two commands. Blank returns in both echoes.

**Comment by dec05eba** [comment] 2024-09-28 18:13
As I thought. Flatpak is not properly setup on your system (dbus). Its likely the cause because you use sway and/or void linux which doesn't do it automatically for you.

**Comment by dec05eba** [comment] 2024-09-28 18:39
On x11 on a systemd distro when using startx you have a system xinit file that contains this:
```
systemctl --user import-environment DISPLAY XAUTHORITY

if command -v dbus-update-activation-environment >/dev/null 2>&1; then
    dbus-update-activation-environment DISPLAY XAUTHORITY
fi
```
which I believe gives you DBUS_SESSION_BUS_ADDRESS. I cant say how you typically do that with sway and runit from void. I'll close this issue. If it still doesn't work after properly setting up flatpak (dbus) on your system then you can reopen this issue.

**Closed by dec05eba** 2024-09-28 18:39 UTC
Labels: bug

**Comment by anischenk0** [comment] 2024-09-28 18:52
> As I thought. Flatpak is not properly setup on your system (dbus). Its likely the cause because you use sway and/or void linux which doesn't do it automatically for you. You can search for "Cannot autolaunch D-Bus without X11 $DISPLAY" online to figure out how to solve it. DBUS_SESSION_BUS_ADDRESS will need to be set automatically. Sometimes it works to set it manually or something, I dont know.

As per [Void Linux Handbook,](https://docs.voidlinux.org/config/session-management.html#d-bus) I've made sure the dbus service was enabled (it already was) and then started sway like this:
`dbus-run-session -- sway`

Now, echo $DBUS_SESSION_BUS_ADDRESS returns
`unix:path=/tmp/dbus-HhoskLIJOu,guid=0c46cbeb9633fb21f954a93c66f8486a`

Running 
`dbus-run-session -- flatpak run --command=gpu-screen-recorder com.dec05eba.gpu_screen_recorder -w screen -f 30 -o video.mp4`
returns:
`dbus-daemon[4212]: [session uid=1000 pid=4212] Activating service name='org.freedesktop.Flatpak' requested by ':1.0' (uid=1000 pid=4213 comm="flatpak run --command=gpu-screen-recorder com.dec0")
dbus-daemon[4212]: [session uid=1000 pid=4212] Successfully activated service 'org.freedesktop.Flatpak'
dbus-daemon[4212]: [session uid=1000 pid=4212] Activating service name='org.a11y.Bus' requested by ':1.0' (uid=1000 pid=4213 comm="flatpak run --command=gpu-screen-recorder com.dec0")
dbus-daemon[4212]: [session uid=1000 pid=4212] Successfully activated service 'org.a11y.Bus'
Warning: failed to connect to the X server. Assuming wayland is running without Xwayland
Info: using h264 encoder because a codec was not specified
gsr info: gsr_kms_client_init: waiting for server to connect
Error creating textual authentication agent: Error opening current controlling terminal for the process ('/dev/tty'): No such device or address
gsr error: gsr_kms_client_init: kms server died or never started, exit code: 127
gsr error: gsr_capture_start failed`

Similarly, `flatpak run --command=gpu-screen-recorder com.dec05eba.gpu_screen_recorder -w screen -f 30 -o video.mp4` now returns:
`Warning: failed to connect to the X server. Assuming wayland is running without Xwayland
Info: using h264 encoder because a codec was not specified
gsr info: gsr_kms_client_init: waiting for server to connect
Error creating textual authentication agent: Error opening current controlling terminal for the process ('/dev/tty'): No such device or address
gsr error: gsr_kms_client_init: kms server died or never started, exit code: 127
gsr error: gsr_capture_start failed`

Doing the steps from:


> Try this, run `ls /dev/dri/card*` to see which files you have available and then use the first one and run:
> 
> ```
> flatpak run --command=bash com.dec05eba.gpu_screen_recorder
> flatpak-spawn --host /var/lib/flatpak/app/com.dec05eba.gpu_screen_recorder/current/active/files/bin/kms-server-proxy blabla /dev/dri/card0 $HOME
> ```
> 
> replace /dev/dri/card0 there with the /dev/dri/cardN file that is available on your computer

On a new terminal looked like this:


`echo $DBUS_SESSION_BUS_ADDRESS`
`unix:path=/tmp/dbus-HhoskLIJOu,guid=0c46cbeb9633fb21f954a93c66f8486a`

`flatpak run --command=bash com.dec05eba.gpu_screen_recorder`

`flatpak-spawn --host /var/lib/flatpak/app/com.dec05eba.gpu_screen_recorder/current/active/files/bin/kms-server-proxy blabla`
`/dev/dri/card0 $HOME`
`Error creating textual authentication agent: Error opening current controlling terminal for the` `process ('/dev/tty'): No such device or address`
`echo $DBUS_SESSION_BUS_ADDRESS`
`unix:path=/run/flatpak/bus`

Sorry about the formatting, I'm not sure why the code (double tildes) don't work correctly. I don't know what I'm doing wrong.

**Comment by dec05eba** [comment] 2024-09-28 18:55
You likely dont have a polkit agent running which is needed for pkexec, as explained in the description for the gpu screen recorder flatpak. You can otherwise try using the portal capture option

**Comment by anischenk0** [comment] 2024-09-28 19:17
Solved.
Polkit was installed, and the service was enabled. As per [this site](https://discussion.fedoraproject.org/t/sway-polkit-on-f37-does-not-work/75474),

> I have sway and polkit running just fine with exec /usr/libexec/polkit-gnome-authentication-agent-1 in the config file

Thus, running the gnome authentication agent allowed the program to request permission before running and eventually start up correctly. Thanks!
