### ISSUE TITLE
[BUG] GPU Screen Recorder failing to start on linux mint 21.3

### ISSUE THREAD

**Issue by KirbYyY1998** [dec05eba/gpu-screen-recorder-issues#70] opened 2024-11-22 06:20 UTC
**Describe the bug**
Since a couple of days ago the software will not start normally, from googling the issue it seems amdgpu is refusing elevated privileges. Tried updating pkexec and polkit but both are up to date, unsure where to continue since I am very inexperienced with linux. Sorry if this is just me being dumb and issue doesn't belong here.

**To Reproduce**
Did not start until I ran the following command:
sudo -i /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=gpu-screen-recorder-gtk com.dec05eba.gpu_screen_recorder

However, I cannot use any of the features as the software instantly closes when trying to record or use the replay function.

**Screenshots**
The following is displayed after I opened the software with sudo -i

![image](https://github.com/user-attachments/assets/846e2f4d-64fc-4ebf-ae87-5f93ce475266)

**Desktop (please complete the following information):**
- X11 or Wayland: X11
- Desktop environment/Window Manager: X-Cinnamon
- Distro: Linux Mint 21.3 Cinnamon (Cinnamon version 6.0.4)
- GPU: AMD Radeon RX6600
- Version (latest flatpak version, aur or source): Latest version from software manager (flatpak)

**Additional context**
If relevant:

I always keep system up to date using the update manager, so all kernel/hardware drivers should be up to date, as well as the GPU Screen Recorder version. It worked without any issues for months until a few days ago.

- [ n ] I played the video with the command `mpv --no-config video.mp4` (if applicable)
- [ n ] I use a laptop with an integrated GPU and a dedicated GPU

**Comment by dec05eba** [comment] 2024-11-22 08:58
The amdgpu error is a warning you can ignore, it's unrelated. I think the real reason is because linux mint doesn't use pipewire audio. I did test with pulseaudio but I guess linux mint has a bit different setup. I'll install linux mint when I have time and test it.

**Comment by dec05eba** [comment] 2024-11-22 16:19
I can reproduce the issue on linux mint 21.3, but it only happens in the flatpak, not when installing gpu screen recorder from source. I'll see if I can figure out why.

**Comment by dec05eba** [comment] 2024-11-22 18:03
The issue has been fixed in git, the fix will be released later in flathub when it gets updated there. Re-open this issue if it doesn't work after updating when it's available (gpu screen recorder version 4.3.3).

**Closed by dec05eba** 2024-11-22 18:03 UTC
Labels: bug
