### ISSUE TITLE
[BUG] Nvidia 2060 Mobile black screen on wayland

### ISSUE THREAD

**Issue by mercifulboss** [dec05eba/gpu-screen-recorder-issues#43] opened 2024-08-14 21:31 UTC
**Describe the bug**
When I click "record" on wayland, I get a black screen but sound is recorded. Even using CLI with the -w command doesn't work. I have to put `prime-run` into Environmental Variables, otherwise the gui doesn't open. In addition, I tried every single video codec available, the outcome does not change - the output is still a black screen. Running the program with `sudo prime-run` only causes it to crash.

**To Reproduce**
![Screenshot_20240814_171942](https://github.com/user-attachments/assets/062cffa0-063c-4e8a-8332-d623072cf4a1)

**Desktop (please complete the following information):**
 - X11 or Wayland: Wayland
- Desktop environment/Window Manager: KDE
 - Distro: Archlinux
 - GPU: Nvidia 2060 mobile
 - Version (latest flatpak version, aur or source): AUR

**Additional context**
Add any other context about the problem here, such as terminal output of running GPU Screen Recorder and if the issue isn't related to audio then please run `sudo drm_info > log.txt` and attach that log.txt file in this bug report. drm_info can be installed from your package manager or from https://gitlab.freedesktop.org/emersion/drm_info.

[log.txt](https://github.com/user-attachments/files/16619066/log.txt)

Attach a video that shows the issue (if applicable), in raw form as output by GPU Screen Recorder or a losslessly cut version of it (you can use https://flathub.org/apps/org.gnome.gitlab.YaLTeR.VideoTrimmer for example to do this).

https://github.com/user-attachments/assets/980d5c3a-908e-4e79-8f9a-6874904e0f98

Which game did you run while recording (if any) and does the issue also happen if you only record your desktop? 

Haven't tried game, only desktop. Wanted to use it primairly for the purpose of doing high quality desktop recordings.

Edit: 

I tried running it with starcraft 2 on default settings, and it only records sound but not video

https://github.com/user-attachments/assets/0304bba3-974d-47ac-8094-cc25fb4de04d

Does the issue also happen if you use obs studio instead with equivalent settings (video encoding settings and audio codec settings. Nvenc on nvidia and vaapi on amd/intel and same video/audio codec)?

No. OBS studio with pipewire works fine to screen record

If you have an issue with audio make sure you are not using pulseaudio/pipewire audio processing software such as EasyEffects.

Audio records fine. Video does not

If you are setting any amd/intel/nvidia/mesa/vaapi/pulseaudio/pipewire environment variables then please list those.

`prime-run`

- [ ] I played the video with the command `mpv --no-config video.mp4` (if applicable)
- [X] I use a laptop with an integrated GPU and a dedicated GPU

**Comment by dec05eba** [comment] 2024-08-15 03:35
For the first error, I see that it says that your laptop monitor is connected but it doesn't seem to display anything. Is the monitor disabled in kde display settings or something?

**Comment by dec05eba** [comment] 2024-08-15 04:02
I have confirmed that the first issue is a bug. It happens when your laptops monitor is disabled. It should work if you enable it, then you can also capture with portal. I'll fix this issue.
Desktop portal capture doesn't seem to work when using prime-run (obs also ends up copying the data to cpu in that case instead so it seems like its more of a pipewire limitation). So that option will have to be disabled when using prime run.
But recording your monitor with prime-run (non desktop portal option) should have worked. Can you run this and copy the terminal output here?: `prime-run gpu-screen-recorder -w screen -f 60 -o video.mp4`

**Comment by mercifulboss** [comment] 2024-08-15 04:12
> prime-run gpu-screen-recorder -w screen -f 60 -o video.mp4

Info: using h264 encoder because a codec was not specified
[h264_nvenc @ 0x627bd183d2c0] ignoring invalid SAR: 0/0
gsr info: gsr_kms_client_init: waiting for server to connect
kms server info: connecting to the client
gsr info: gsr_kms_client_init: server connected
gsr info: replacing file-backed unix domain socket with socketpair
kms server info: connected to the client
gsr info: using socketpair
[h264_nvenc @ 0x627bd183d2c0] ignoring invalid SAR: 0/0
update fps: 245, damage fps: 245
update fps: 246, damage fps: 246
update fps: 246, damage fps: 246
update fps: 246, damage fps: 246
update fps: 247, damage fps: 247
update fps: 246, damage fps: 246
update fps: 246, damage fps: 246

**Comment by dec05eba** [comment] 2024-08-15 04:16
can you upload that raw video.mp4 file here?

**Comment by mercifulboss** [comment] 2024-08-15 04:16
> can you upload that raw video.mp4 file here?

https://github.com/user-attachments/assets/836cd2ba-7120-4b15-896c-cac1dab1c555

**Comment by mercifulboss** [comment] 2024-08-15 04:17
> can you upload that raw video.mp4 file here?


https://github.com/user-attachments/assets/b2b87212-0849-4ef2-9cdd-4e8148a2e2f1

**Comment by dec05eba** [comment] 2024-08-15 04:25
Can you try this:
```
git clone https://repo.dec05eba.com/gpu-screen-recorder
cd gpu-screen-recorder
git checkout e4832f3d643abf8adf1f5872614b020c833afd0b
sudo ./install.sh
```

and try `prime-run gpu-screen-recorder -w screen -f 60 -o video.mp4` again?
(after that you can revert back to the latest version by installing gpu screen recorder from aur again).

**Comment by mercifulboss** [comment] 2024-08-15 04:30
prime-run gpu-screen-recorder -w screen -f 60 -o video.mp4
[hevc_nvenc @ 0x5aa295cefac0] ignoring invalid SAR: 0/0
Info: using hevc encoder because a codec was not specified
gsr info: gsr_kms_client_init: waiting for server to connect
kms server info: connecting to the client
gsr info: gsr_kms_client_init: server connected
gsr info: replacing file-backed unix domain socket with socketpair
kms server info: connected to the client
gsr info: using socketpair
[hevc_nvenc @ 0x5aa295cefac0] ignoring invalid SAR: 0/0
update fps: 246
update fps: 246
update fps: 247
update fps: 246
update fps: 246
update fps: 247
update fps: 247
update fps: 247
update fps: 247


There is no video output. I deleted the previous file and no new `video.mp4` file shows up in the $HOME directory

**Comment by dec05eba** [comment] 2024-08-15 04:41
Ok thanks. Can you try this in that directory:
```
git checkout master
git pull
sudo ./install.sh
```
and try recording again? i added some debug outputs.

**Comment by mercifulboss** [comment] 2024-08-15 04:46
> Ok thanks. Can you try this in that directory:
> 
> ```
> git checkout master
> git pull
> sudo ./install.sh
> ```
> 
> and try recording again? i added some debug outputs.

I put each command in line by line, it did some installing and then put the command `prime-run gpu-screen-recorder -w screen -f 60 -o video.mp4`

![image](https://github.com/user-attachments/assets/1fec375f-8226-4998-8f02-4c195202b0ff)

**Comment by dec05eba** [comment] 2024-08-15 04:47
im pretty sure there is a video.mp4 file in that directory, but its likely black anyways

**Comment by mercifulboss** [comment] 2024-08-15 04:50
> im pretty sure there is a video.mp4 file in that directory, but its likely black anyways

I ran the command again. I am checking the /home/ directory but don't see anything? perhaps its the wrong directory?

**Comment by dec05eba** [comment] 2024-08-15 04:51
the video is in the directory you run the video in (gpu-screen-recorder)

**Comment by mercifulboss** [comment] 2024-08-15 04:53
> the video is in the directory you run the gpu-screen-recorder command in (gpu-screen-recorder)

Ah apologies. Silly of me. I found it.


https://github.com/user-attachments/assets/62f3f169-0f3c-43e4-a09b-b2c2d81b2e4a

**Comment by dec05eba** [comment] 2024-08-15 05:13
ok i added more debug log. Can you try `git pull` again and record again?

**Comment by mercifulboss** [comment] 2024-08-15 05:26
> ok i added more debug log. Can you try `git pull` again and record again?

![image](https://github.com/user-attachments/assets/b868a128-9af8-42b3-8cc6-c0bce99f7e0c)

Deleted the old `video.mp4` video. Here is the new one:

https://github.com/user-attachments/assets/1f72651b-6497-4aa3-947b-48c9771e5587

**Comment by dec05eba** [comment] 2024-08-15 07:53
Can you do `git pull`, then `sudo ./install.sh` and try, checking if the video works after each command:
`gpu-screen-recorder -w portal -f 60 -o video.mp4`
`prime-run gpu-screen-recorder -w portal -f 60 -o video.mp4`
`prime-run gpu-screen-recorder -w screen -f 60 -o video.mp4`

**Comment by dec05eba** [comment] 2024-08-15 18:00
Im working on re-designing the UI so it works like shadowplay where you have the option to start it on system startup and can press a hotkey at any time to start recording, etc. At the moment you have some options. Unfortunately wayland makes it painful/impossible, but at least it should work on kde plasma wayland.

If you want the hotkey for replay then you can start the systemd service included in the aur package, with `systemctl enable --now --user gpu-screen-recorder`. There is more info about that here: https://git.dec05eba.com/gpu-screen-recorder/about/.

If you want to start regular recording with a hotkey then you can go to KDE shortcuts setting in the system settings menu and choose which command to run when a hotkey is pressed. With that you can bind a key to run this script with prime-run: https://git.dec05eba.com/gpu-screen-recorder/tree/scripts/start-recording.sh and bind another key to run this script: https://git.dec05eba.com/gpu-screen-recorder/tree/scripts/save-recording.sh to save the recording.

But anyways, the issues reported here are fixed now right? as for the quality, yes nvidia has superior encoder quality. If you want better quality on intel (or even on nvidia) you can switch to another video codec in the settings. h264 is the default which is actually kinda the worst, but it works best. If your intel/nvidia gpu supports hevc then choose that instead, or av1 which is even better. vp8/vp9 might even be better than h264. Or just choose ultra quality in the settings.

**Comment by mercifulboss** [comment] 2024-08-15 18:01
> Im working on re-designing the UI so it works like shadowplay where you have the option to start it on system startup and can press a hotkey at any time to start recording, etc. Unfortunately wayland makes it painful/impossible, but at least it should work on kde plasma wayland. Before that is done you have some options other options:
> 
> If you want the hotkey for replay then you can start the systemd service included in the aur package, with `systemctl enable --now --user gpu-screen-recorder`. There is more info about that here: https://git.dec05eba.com/gpu-screen-recorder/about/.
> 
> If you want to start regular recording with a hotkey then you can go to KDE shortcuts setting in the system settings menu and choose which command to run when a hotkey is pressed. With that you can bind a key to run this script with prime-run: https://git.dec05eba.com/gpu-screen-recorder/tree/scripts/start-recording.sh and bind another key to run this script: https://git.dec05eba.com/gpu-screen-recorder/tree/scripts/save-recording.sh to save the recording.
> 
> But anyways, the issues reported here are fixed now right? as for the quality, yes nvidia has superior encoder quality. If you want better quality on intel (or even on nvidia) you can switch to another video codec in the settings. h264 is the default which is actually kinda the worst, but it works best. If your intel/nvidia gpu supports hevc then choose that instead, or av1 which is even better. vp8/vp9 might even be better than h264. Or just choose ultra quality in the settings.

Thank you for fixing this so fast. It seems to work. I really appreciate it. Do you have an approximate ETA for the redesign (no rush just curious)?

**Comment by dec05eba** [comment] 2024-08-15 18:04
It will take a while, because im not working actively on it. Its not something you should wait for on your seat.
KDE plasma supports global hotkeys on wayland yes, but no other wayland compositor does (hyprlands implementation is buggy and doesn't work in the same way, the kde plasma shortcut is also buggy but at least it works).

**Closed** 2024-08-15 18:09 UTC
Labels: bug
