### ISSUE TITLE
[BUG] Higher audio latency after fixes for audio desync

### ISSUE THREAD

**Issue by Stoppedpuma** [dec05eba/gpu-screen-recorder-issues#9] opened 2024-04-11 18:15 UTC
**Describe the bug**
Audio latency is roughly twice as much after commits for fixing audio desync issues

**To Reproduce**
gpu-screen-recorder -w screen -f 120 -a "$(pactl get-default-sink).monitor" -cr full -fm cfr -ac opus -k hevc -q very_high -o ~/videos/video.mkv

**Expected behavior**
Lower audio latency

**Screenshots**
"nodesync-build" uses the commits that fixed the audio desync. "desync-build" is the build I used to report #7. the lines show when it appears on video, the waveform shows the audio.

![1712858323](https://github.com/dec05eba/gpu-screen-recorder-issues/assets/58333920/15a8b0ef-d65f-46fd-a49a-69d59109733b)

**Desktop (please complete the following information):**
 - X11 or Wayland: Wayland
- Desktop environment/Window Manager: Sway
 - Distro: Debian
 - GPU: Radeon RX 6700XT
 - Version: Source

- [x] I played the video with the command `mpv --no-config video.mp4` (if applicable)
- [ ] I use a laptop with an integrated GPU and a dedicated GPU

**Comment by dec05eba** [comment] 2024-04-11 18:25
Just for reference, what is the audio latency like with obs studio when compared in the same way when recording at 120 fps?

**Comment by Stoppedpuma** [comment] 2024-04-11 18:36
It's nearly in the middle of the two, I do have obs recording multiple audio tracks (all of which are the same on timing) so I don't know if that affects latency for obs or not.

![1712860435](https://github.com/dec05eba/gpu-screen-recorder-issues/assets/58333920/55bdb9bd-c62b-4a31-af9a-b80a9715fcae)

**Comment by dec05eba** [comment] 2024-04-11 19:11
Ok thanks so it might not be possible to sync audio 100% with video if other screen recorders cant do it either, but I know what I can do to improve it at least. I'll test some things when I have time.
Just a question, what type of audio output device are you recording with? is it a bluetooth device, speakers, analog headset or what?

**Comment by Stoppedpuma** [comment] 2024-04-11 19:18
My output device is my headphones being plugged into the 3.5mm headphone jack on my motherboard.
I'm using pipewire with a minimum quantum of 16 and the following allowed clock rates: `44100 48000 88200 96000 176400 192000`

**Comment by dec05eba** [comment] 2024-04-12 14:42
I think one of the reasons for this might be that opus is temporary disabled and with aac a larger audio buffer is used so it might take a tiny bit longer to fill the audio buffer before its saved. But this should be fixable.

**Comment by dec05eba** [comment] 2024-04-15 18:28
Hmm I tested this and I cant reproduce it myself (with the command you used). I pretty much dont have any audio/video desync with the latest commit, kdenlive displays the video and audio at the exact same time. I tested with this: https://www.youtube.com/watch?v=ucZl6vQ_8Uo. I tested with taking latency into account but there wasn't any noticable difference.
I do have latency if I use my bluetooth device but I get the same latency in all audio recording software with that device and I can fix that by changing latency offset in pavucontrol for the output device.

**Comment by Stoppedpuma** [comment] 2024-04-16 04:30
I'll test the new commit now.

Were you using a 120 fps preset on kdenlive during your testing?

**Comment by Stoppedpuma** [comment] 2024-04-16 05:07
New commit doesn't seem to help? On kdenlive I noticed it was inconsistent between 8-10 moves on the waveform on the new commit (I don't recall it being inconsistent before but I might be wrong), I'm also receiving an error I've not had before on the new commit `amdgpu: amdgpu_cs_ctx_create2 failed. (-13)` 

I'll post some comparisons of the build which fixed the desync issue, this new commit, and obs.

**Comment by Stoppedpuma** [comment] 2024-04-16 06:26
@dec05eba Question, I'm assuming you're not aware of gpu-screen-recorder basically just giving up on trying to output the correct framerate when using stupidly high values such as 240? Should I open another issue for this? I'm able to record just fine at 240 fps on obs.

**Comment by dec05eba** [comment] 2024-04-16 06:38
@Stoppedpuma it's likely a hardware limitation with your gpu. are you recording with nvenc and hevc on obs? you can switch codec to record at higher fps

**Comment by Stoppedpuma** [comment] 2024-04-16 07:21
200fps seems to be where things break if I go above it. On OBS I'm able to record 240fps at 1440p, gpu-screen-recorder can't seem to? Both are using vaapi hevc for encoding

**Comment by Stoppedpuma** [comment] 2024-04-16 15:21
When going frame by frame in mpv, obs seems to output 240? Maybe I'm misunderstanding this option in obs?

![1713280880](https://github.com/dec05eba/gpu-screen-recorder-issues/assets/58333920/26f9525f-293e-4ba5-9ea2-b7c83b81849c)

**Comment by dec05eba** [comment] 2024-04-16 15:26
> When going frame by frame in mpv, obs seems to output 240? Maybe I'm misunderstanding this option in obs?
> 
> ![1713280880](https://private-user-images.githubusercontent.com/58333920/322903610-26f9525f-293e-4ba5-9ea2-b7c83b81849c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyODE0MDYsIm5iZiI6MTcxMzI4MTEwNiwicGF0aCI6Ii81ODMzMzkyMC8zMjI5MDM2MTAtMjZmOTUyNWYtMjkzZS00YmE1LTllYTItYjdjODNiODE4NDljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDE1MjUwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhZGQ1NzM5MDlkYTQ3NTc5ZjVhNGE3NDkyMWFjYjQ5M2VmNTkzNWM4MDk3MTQwZWI5MWQ4NjYwYjdlYjQwNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lUouA0BGo7Q0JyFEA8PmhWREtOh71qwQ3jpd-RnlkIQ)
> 
> Just to make sure you're seeing the same behaviour on your end, if you record with gpu-screen-recorder at 240fps it just outputs like 15 fps for you as well correct?

it does that if you record with constant frame rate and the encoder cant keep up, the same thing happens in obs studio with constant frame rate. I just tested with obs studio and i got an encoder warning and the actual video framerate is 15 fps but the files reported fps is 240fps

**Comment by dec05eba** [comment] 2024-04-16 15:34
I see what you mean with the audio quality now when you recorded with osu. Also the video/audio timing seems weird for you, i'll check if i can reproduce that myself in osu

**Comment by Stoppedpuma** [comment] 2024-04-16 15:38
> Also the video/audio timing seems weird for you

I was about to run tests on the classic version of osu! because I was wondering if half of the reason the osu! tests seem so different to the rest was just the bass.net latency and it not using my pipewire quantum, I'll upload tests from the old version with a offset I'm 99% sure is correct as well as it using my quantum of 16 (lazer can't do this until [this is merged](https://github.com/ppy/osu-framework/pull/6002))

**Comment by dec05eba** [comment] 2024-04-16 15:39
>The video file shows 120 fps but it doesn't look like 120 fps when compared to obs and the desync fix build? This might just be from an issue on my end or my eyes tricking me but I'll do more tests spread across more applications, videos, etc for both.
you are right, you can do frame by frame step and it repeats some frames. I will revert the commit. But I have read that wlroots has an issue with frame pacing sometimes at around 120 fps so i'll check myself if i can reproduce it

**Comment by dec05eba** [comment] 2024-04-16 16:02
I didn't reproduce that issue. Im not sure if it's because you re-encoded the video or if wlroots introduced that issue

**Comment by dec05eba** [comment] 2024-04-16 16:18
> None of the videos I posted above were re-encoded, most likely wlroots then.

oh i assumed so because of the title text, but is that done is osu then? but anyways i reverted the commit that changes the latency. In my own test it doesn't really impact audio latency itself in a better way. I also merged your commit to change default audio bitrate.

**Comment by dec05eba** [comment] 2024-04-16 16:28
Also I tested with correct kdenlive preset and higher resolution video/audio sync test (osu is too noisy with audio to analyze it) and the latency for me is the same with obs and gpu screen recorder. I dont know if its maybe an issue with how frames are captured on wlroots instead. I assume you used pipewire with obs. gpu screen recorder uses a different method and I recorded on X11 instead.

**Comment by dec05eba** [comment] 2024-04-16 17:00
maybe, but that offset wizard looks to have the same latency as obs and gpu screen recorder for me (when I record). The obs offset wizard you posted is a broken link

**Closed** 2024-04-16 17:04 UTC
Labels: bug

**Comment by Stoppedpuma** [comment] 2024-04-16 17:06
Would your original guess of audio buffers matter still?

**Comment by dec05eba** [comment] 2024-04-16 17:13
i tested and audio buffer didn't seem to change the audio/video sync. And for the obs recording I meant that its more accurate for your than for me (for me it has the exact same latency as gpu screen recorder), and if that is because you have changed some obs settings or because of multiple audio tracks i dunno.

**Comment by dec05eba** [comment] 2024-04-16 17:13
Oh I think I know what it can be... the latency is affected by the devices you record. Which devices did you record in obs studio?

**Comment by Stoppedpuma** [comment] 2024-04-16 17:14
My multiple tracks contain the following:

Track 1: Desktop and Mic
Track 2: Desktop
Track 3: Mic

**Comment by dec05eba** [comment] 2024-04-16 17:16
i dont know if you can just compare the track alone. Obs might have some track syncing going on.

**Comment by Stoppedpuma** [comment] 2024-04-16 17:17
Wait I might be stupid and possibly know what it is, gpu-screen-recorder records at 44.1khz, my obs profile records at 48khz. Sample rates affect pipewire latency so maybe this could be it?

**Comment by Stoppedpuma** [comment] 2024-04-16 17:19
I must have misread 44.1khz some where then, I'll do single track testing.

I still do have the `amdgpu: amdgpu_cs_ctx_create2 failed. (-13)` error from latest commit, should I open this as another issue or is this a quick fix?

**Comment by dec05eba** [comment] 2024-04-16 17:21
thats a random warning that amd driver outputs, it has done that for a long time. I dont know exactly when it happens but it has no effect. Its caused by cap_sys_nice+ep that gpu screen recorder uses.

**Comment by dec05eba** [comment] 2024-04-16 17:24
https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3543#note_1661557 it's this warning, it's harmless. But that shouldn't appear if you run gpu screen recorder after you install it with sudo ./install.sh. Are you instead building it and then running it from the same directory?

**Comment by dec05eba** [comment] 2024-04-16 17:30
> I must have misread 44.1khz some where then, I'll do single track testing.
> 

it might not just be single track but other obs settings you have changed. I dont know if its worth testing without resetting obs to default. But its ok, you dont have to go through the trouble for that. I believe from the video you posted that it's not an issue in gpu screen recorder as it matches obs for me.

**Comment by Stoppedpuma** [comment] 2024-04-16 17:50
> But that shouldn't appear if you run gpu screen recorder after you install it with sudo ./install.sh. Are you instead building it and then running it from the same directory?

Didn't even think of that being a reason, fixed after install.

> Did you also do that in obs studio?

I didn't add the audio as a source, I chose my output in settings so whichever one that uses?

![1713289728](https://github.com/dec05eba/gpu-screen-recorder-issues/assets/58333920/1d91fcc7-fa11-420b-96ce-cf83ddbea4b1)

**Comment by dec05eba** [comment] 2024-04-16 18:13
that only seems to make a difference in microseconds so I dont think so. But obs syncs well for me now as well, I dont know what I changed.. But I pushed a change to gpu screen recorder. Can you try it? if it doesn't work well then fuck it

**Comment by dec05eba** [comment] 2024-04-16 18:37
I added a hardcoded value that it shifts the audio by. Hey, if it works it works lol

**Comment by Stoppedpuma** [comment] 2024-04-16 18:37
![1713292637](https://github.com/dec05eba/gpu-screen-recorder-issues/assets/58333920/529aedfe-0773-4667-acb4-251369efd5a0)

**Comment by dec05eba** [comment] 2024-04-16 18:43
Thanks for testing. I'll go with this until somebody complains that it broke audio sync for them xd
