### ISSUE TITLE
[BUG] Not all monitors detected on a multi-GPU system.

### ISSUE THREAD

**Issue by jackmio32** [dec05eba/gpu-screen-recorder-issues#27] opened 2024-06-21 21:04 UTC
**Describe the bug**
I am running 3 monitors across 2 GPUs. My gaming/main monitor is hooked up to my main GPU, an RX 6800, and my other 2 monitors are hooked up to my secondary GPU, a RX 5500XT. When I run GPU Screen Recorder, it only detects my two monitors on my secondary GPU, and doesn't seem to be aware of my main monitor/GPU at all, as no option for them are shown.

**To Reproduce**
No special run conditions/options, besides being on a multi-monitor multi-GPU system.

**Screenshots**
![Screenshot_20240621_160650](https://github.com/dec05eba/gpu-screen-recorder-issues/assets/15147460/062a5092-2053-4c07-8f98-d54c56fbe5bb)
Edit: Screenshot did not show the context menu correctly, so I got another one.

**Desktop (please complete the following information):**
 - X11 or Wayland: Wayland
- Desktop environment/Window Manager: KDE Plasma
 - Distro: Kubuntu
 - GPU: RX 6800 (main), RX 5500XT
 - Version (latest flatpak version, aur or source): Flatpak version

**Additional context**
When ran from a terminal, the only output is `amdgpu: amdgpu_cs_ctx_create2 failed. (-13)`

- [ ] I played the video with the command `mpv --no-config video.mp4` (if applicable)
- [ ] I use a laptop with an integrated GPU and a dedicated GPU

**Comment by dec05eba** [comment] 2024-06-21 21:11
gpu screen recorder does currently not support selecting which gpu is used, it will select the "default" one. You can try setting this environment variable before you run gpu screen recorder: https://docs.mesa3d.org/envvars.html#envvar-DRI_PRIME to the other gpu (maybe try `export DRM_PRIME=1`). Also please dont ignore the report template (the part about drm_info).

**Comment by dec05eba** [comment] 2024-06-21 21:48
Thanks, can you try that DRM_PRIME environment variable option? I dont have a system with two gpus so I cant test it myself. But I also want to clearify that it's not a bug, it's a missing feature (option) to select which gpu to use, so I'll close this issue but I also want to know if that DRM_PRIME environment variable is a temporary solution that can be used.

**Comment by dec05eba** [comment] 2024-06-21 21:52
Run it from the terminal to see if there is any error. But maybe DRM_PRIME option doesn't really work.

**Comment by dec05eba** [comment] 2024-06-21 22:06
Can you run `eglgears_wayland` with DRI_PRIME=1? maybe the option doesn't work at all

**Comment by dec05eba** [comment] 2024-06-21 22:13
Running gpu screen recorder (gui) as root is not supported and wayland doesn't support running graphical applications as root anyways

**Comment by dec05eba** [comment] 2024-06-21 22:14
Can you try running `flatpak run --command=gpu-screen-recorder com.dec05eba.gpu_screen_recorder -w screen -f 60 -o video.mp4` instead, with and without `DRM_PRIME=1`?

**Comment by dec05eba** [comment] 2024-06-21 22:37
Hmm, can you try `flatpak run --env=DRI_PRIME=1 --command=gpu-screen-recorder com.dec05eba.gpu_screen_recorder -w screen -f 60 -o video.mp4` instead? and remove the DRI_PRIME=1 that you set before

**Comment by dec05eba** [comment] 2024-06-21 22:46
Alright then I dont know. I guess you will have to wait until I add support for selecting the gpu in gpu screen recorder instead. Unfortunately I dont have a system with two amd gpus so I cant do this right now.

**Closed by dec05eba** 2024-06-21 22:46 UTC
Labels: bug
